### PR TITLE
Adds waiting behaviour

### PR DESCRIPTION
**Pull request by Sunwards**

### CODE REVIEW

**Review by leocavalcante — APPROVED** [review]

**Comment by leocavalcante** [comment]
@Sunwards, can you help with the conflicts, please?

**Comment by Sunwards** [comment]
> @Sunwards, can you help with the conflicts, please?

**Comment by Sunwards** [comment]
> @Sunwards, can you help with the conflicts, please?

@leocavalcante sure, done

**Comment by leocavalcante** [comment]
Thank you!

**Pull request merged**
