### PR TITLE
Add RabbitMQContainer

### PR DESCRIPTION
**Pull request by flavioheleno**
This PR adds a new RabbitMQContainer class that exposes a `RabbitMQ` module.

### CODE REVIEW

**Comment by flavioheleno** [comment]
@leocavalcante do not merge this yet, I'll replace the tests using `php-amqp/php-amqp` with a library instead :)

**Comment by flavioheleno** [comment]
@leocavalcante I can't figure out why the tests are failing..they all pass when I run locally, could you advise please?

**Comment by leocavalcante** [comment]
```
    Problem 1
      - php-amqplib/php-amqplib is locked to version v3.6.1 and an update of this package was not requested.
      - php-amqplib/php-amqplib v3.6.1 requires ext-sockets * -> it is missing from your system. Install or enable PHP's sockets extension.
```

I'll be adding it to the `phpctl` dev container variant.

**Comment by leocavalcante** [comment]
There we go: https://github.com/opencodeco/phpctl/commit/ee2ff476502738042b450d0a25b71e036f78adda
Feel free to merge it when you think it is ready, @flavioheleno :)

**Review by leocavalcante — APPROVED** [review]

**Comment by flavioheleno** [comment]
oh boy, did not scroll the log enough to see the error message.. *facepalm* sorry & thanks Leo!

**Pull request merged**
